[package]
name = "application"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
infrastructure = { path = "../infrastructure" }
domain = { path = "../domain" }
shared = { path = "../shared" }

thiserror.workspace = true
validator.workspace = true
serde.workspace = true
argon2.workspace = true
chrono.workspace = true
tokio.workspace = true
jsonwebtoken.workspace = true
rand.workspace = true
sha2.workspace = true
uuid.workspace = true
hex.workspace = true
base64.workspace = true
ctutils.workspace = true
time.workspace = true